"$schema" = 'https://starship.rs/config-schema.json'

# Prompt
add_newline = false
format = '$all' # default

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1
use_logical_path = false

[git_branch]
# symbol = ' '
# symbol = ' '
symbol = ''
format = '[\($symbol$branch(:$remote_branch)\)]($style) '

[git_status]
conflicted = 'U'
ahead = '↑$count'
behind = '↓$count'
# diverged = '↕'
diverged = '↓$behind_count↑$ahead_count'
up_to_date = ''
untracked = '?'
stashed = 'S'
modified = 'M'
staged = '+'
# staged = 'A'
renamed = 'R'
deleted = 'D'
typechanged = 'T'

[line_break]
disabled = true

[character]
# success_symbol = '[➜](bold green)'
# error_symbol = '[➜](bold red)'
# error_symbol = '[✗](bold red) '
success_symbol = '[→](bold green)'
error_symbol = '[→](bold red)'
vimcmd_symbol = '[←](bold blue)'
# The following only work in fish shell
# vimcmd_replace_one_symbol = '[←](bold purple)'
# vimcmd_replace_symbol = '[←](bold purple)'
# vimcmd_visual_symbol = '[←](bold yellow)'

[custom.obsidian]
detect_folders = ['.obsidian']
format = '󰍔 '

[custom.claude]
detect_folders = ['.claude']
detect_files = ['CLAUDE.md']
# format = ' '
format = '✧ '

